In [1]:
from google.colab import drive
drive.mount("/content/gdrive/", force_remount=True)

%cd '/content/gdrive/MyDrive/LDS6_S7CN_KieuTriDang/Demo/Chapter3_Logistic_Regression' 

Mounted at /content/gdrive/
/content/gdrive/MyDrive/LDS6_S7CN_KieuTriDang/Demo/Chapter3_Logistic_Regression


In [2]:
import numpy as np
import pandas as pd

In [3]:
X = np.array([["Red", "Sports", "Domestic"],
              ["Red", "Sports", "Domestic"], 
              ["Red", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Imported"],
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Domestic"],
              ["Red", "SUV", "Imported"], 
              ["Red", "Sports", "Imported"]])
Y = np.array(["Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "No", "Yes"])

In [4]:
X = pd.DataFrame(X, columns = ['colors', 'type', 'origin'])
X_now = pd.get_dummies(X)
X_now

colors_Red  colors_Yellow  ...  origin_Domestic  origin_Imported
0           1              0  ...                1                0
1           1              0  ...                1                0
2           1              0  ...                1                0
3           0              1  ...                1                0
4           0              1  ...                0                1
5           0              1  ...                0                1
6           0              1  ...                0                1
7           0              1  ...                1                0
8           1              0  ...                0                1
9           1              0  ...                0                1

[10 rows x 6 columns]

In [5]:
Y = pd.DataFrame(Y, columns = ['stolen'])
Y_now = pd.get_dummies(Y, drop_first = True)
Y_now

stolen_Yes
0           1
1           0
2           1
3           0
4           1
5           0
6           1
7           0
8           0
9           1

In [6]:
# Using Bernoulli NB
from sklearn.naive_bayes import BernoulliNB
clf_bernoulli = BernoulliNB()
clf_bernoulli.fit(X_now, Y_now)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [7]:
X_new = [[1,0,1,0,1,0], [0,1,0,1,0,1]]
predicted = clf_bernoulli.predict(X_new)
predicted

array([0, 1], dtype=uint8)

In [8]:
# Using Gaussian Classifier
from sklearn.naive_bayes import GaussianNB
clf_gaussian = GaussianNB()
clf_gaussian.fit(X_now, Y_now)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
predicted = clf_gaussian.predict(X_new)
predicted

array([0, 1], dtype=uint8)

In [10]:
# Using MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
text_data = np.array(['I love Vietnam. Vietnam!',
                      'Vietnam is the best',
                      'Ho Chi Minh is the biggest city of Vietnam'])

In [12]:
# Create target vector
y = np.array([0, 0, 1])

In [13]:
# Create bag of words
count = CountVectorizer()
count.fit(text_data)
bag_of_words = count.transform(text_data)
bag_of_words

<3x11 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [14]:
# Create feature matrix
X = bag_of_words.toarray()
X

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1]])

In [15]:
clf_multinomial = MultinomialNB()

multinomial_model = clf_multinomial.fit(X, y)
print("The prediction accuracy is: ", multinomial_model.score(X,y) * 100, "%")

The prediction accuracy is:  100.0 %


In [16]:
test_data = np.array(['Vietnam is beautiful country',
                      'Ho Chi Minh is one of the biggest city'])

X_test = count.transform(test_data)
X_test

<2x11 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [17]:
y_pred = multinomial_model.predict(X_test)
y_pred

array([0, 1])

# Save model to file

In [18]:
import pickle
pkl_filename = 'model_city_classification.pkl'
with open(pkl_filename, 'wb') as file:
  pickle.dump(multinomial_model, file)

In [19]:
# Read model
with open(pkl_filename, 'rb') as file:
  saved_model = pickle.load(file)