In [1]:
!pip install pandas-profiling==2.7.1

     |████████████████████████████████| 256kB 3.6MB/s 
     |████████████████████████████████| 1.1MB 37.4MB/s 
     |████████████████████████████████| 3.2MB 50.6MB/s 
     |████████████████████████████████| 61kB 5.2MB/s 
     |████████████████████████████████| 81kB 7.5MB/s 
     |████████████████████████████████| 296kB 33.6MB/s 
  Created wheel for phik: filename=phik-0.11.2-cp37-none-any.whl size=1107413 sha256=c41101a80004b657e41b4ab0099936fba939797718aae08005e2f9e6e729eb57
  Stored in directory: /root/.cache/pip/wheels/c0/a3/b0/f27b1cfe32ea131a3715169132ff6d85653789e80e966c3bf6
  Created wheel for htmlmin: filename=htmlmin-0.1.12-cp37-none-any.whl size=27085 sha256=8ad33580ba5bf85ad5fb18f29bc4bf1bbcb5b0b0fe3206632a92181e78ae11a9
  Stored in directory: /root/.cache/pip/wheels/43/07/ac/7c5a9d708d65247ac1f94066cf1db075540b85716c30255459
Successfully built phik htmlmin
ERROR: phik 0.11.2 has requirement scipy>=1.5.2, but you'll have scipy 1.4.1 which is incompatible.
  Found existing in

# Chapter 3 - Ex1: Marketing Data
Cho dữ liệu MarketingData.csv chứa số tiền chi tiêu hàng năm của 20.000 khách hàng của một công ty bán lẻ lớn. Nhóm tiếp thị của công ty đã sử dụng các kênh khác nhau để bán hàng hóa và đã phân loại khách hàng dựa trên các giao dịch mua được thực hiện bằng các kênh khác nhau, như sau: 0-Retail (Bán lẻ), 1-Road Show, 2-Social Media và 3-Televison.
Là phụ trách bộ phận Sale, bạn được giao nhiệm vụ xây dựng một mô hình Machine Learning có thể dự đoán kênh hiệu quả nhất có thể được sử dụng để nhắm mục tiêu khách hàng dựa trên chi tiêu hàng năm cho các sản phẩm (features) do công ty bán: Fresh (sản phẩm tươi sống), Milk(sữa), Grocery (tạp hóa), Frozen (sản phẩm đông lạnh), Detergents_Paper (chất tẩy rửa và giấy) và Delicassen (đồ ăn nhanh).

In [2]:
from google.colab import drive
drive.mount("/content/gdrive/", force_remount=True)

%cd '/content/gdrive/MyDrive/LDS6_S7CN_KieuTriDang/BaiTapMachinLearning/Chapter3_Logistic_Regression'

Mounted at /content/gdrive/
/content/gdrive/MyDrive/LDS6_S7CN_KieuTriDang/BaiTapMachinLearning/Chapter3_Logistic_Regression


In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv('./MarketingData.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Fresh             20000 non-null  float64
 1   Milk              20000 non-null  float64
 2   Grocery           20000 non-null  float64
 3   Frozen            20000 non-null  float64
 4   Detergents_Paper  20000 non-null  float64
 5   Delicassen        20000 non-null  float64
 6   Channel           20000 non-null  int64  
dtypes: float64(6), int64(1)
memory usage: 1.1 MB


In [5]:
data.head()

Fresh         Milk  ...   Delicassen  Channel
0  6623.613537  5513.093240  ...  5179.234947        2
1  5642.542497  5829.866565  ...  4327.423268        2
2  5292.078175  6634.370556  ...  4887.560190        2
3  5595.227928  4754.860698  ...  4268.641413        0
4  5126.693267  6009.649079  ...  5097.491872        2

[5 rows x 7 columns]

In [6]:
import pandas_profiling as pp
profile = pp.ProfileReport(data)
profile

Output hidden; open in https://colab.research.google.com to view.

### Logistic Regression

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix

def logistic_regression (X, y, test_size):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size)
  log_reg = LogisticRegression()
  log_reg.fit(X_train, y_train)
  y_pred = log_reg.predict(X_test)

  mse = mean_squared_error(y_test, y_pred)
  mae = mean_absolute_error(y_test, y_pred)
  test_score = log_reg.score(X_test, y_test)
  train_score = log_reg.score(X_train, y_train)
  variance_score = log_reg.score(X, y)
  conf_matrix = confusion_matrix(y_test, y_pred)

  print('Cofficient: ', log_reg.coef_)
  print('Intercept: ', log_reg.intercept_)
  print('Mean Square Error: ', mse)
  print('Mean Absolute Error: ', mae)
  print('Variance Score: ', variance_score)
  print('Train Score: ', train_score)
  print('Test score: ', test_score)
  print('\nConfusion Matrix:')
  print(conf_matrix)

  return log_reg

In [24]:
X = data.drop(columns=['Channel'])
y = data['Channel']

In [25]:
log_reg = logistic_regression(X, y, 0.2)

Cofficient:  [[ 1.21752251e-03  3.90309071e-05 -1.40280310e-03 -6.53572359e-04
   3.72710245e-04  1.76147190e-04]
 [ 3.46136845e-04 -1.42826297e-04 -2.06951153e-04 -1.90207177e-05
   4.82946690e-04 -3.49662838e-04]
 [ 2.51911226e-04  7.99659393e-04  1.69162466e-04  5.02286966e-05
  -5.80037416e-04 -6.41351508e-04]
 [-1.81557058e-03 -6.95864003e-04  1.44059179e-03  6.22364380e-04
  -2.75619519e-04  8.14867157e-04]]
Intercept:  [ 2.66282539e-07  2.87893316e-08  2.93189915e-08 -3.24390862e-07]
Mean Square Error:  0.7885
Mean Absolute Error:  0.457
Variance Score:  0.6764
Train Score:  0.6753125
Test score:  0.68075

Confusion Matrix:
[[664 184  86  70]
 [196 507 186 102]
 [ 87 186 684  33]
 [ 42  52  53 868]]


### Nhận xét:
Theo confusion matrix cho thấy thì channel hiệu quả nhất là: 3 (Television)